# ΕΚΔΔΑ - ΑΝΑΛΥΣΗ ΔΕΔΟΜΕΝΩΝ ΜΕ ΤΗ ΓΛΩΣΣΑ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΥ PYTHON

Ονοματεπώνυμο επιμορφούμενου: Βάγια Γιαννακοπούλου

## Εβδομάδα 3

Στόχος: Να εφαρμόσεις *ολόκληρο* το ρεπερτόριο παραδειγμάτων από το Part A του NumPy πάνω σε ένα ενιαίο πρόβλημα.

**Δεδομένα:** Θα δουλέψεις με μετρήσεις ομάδων ατόμων. Κάθε άτομο έχει 2 χαρακτηριστικά: `[ύψος_cm, βάρος_kg]`.
Θα δημιουργήσεις 3 ομάδες με 5 άτομα η καθεμία.


## 0) Έτοιμο περιβάλλον

In [ ]:
import numpy as np
np.set_printoptions(suppress=True)  # καθαρή εκτύπωση


## 1) Δημιουργία πινάκων (1D, 2D, 3D) & ειδικοί πίνακες

1. Φτιάξε έναν 1D πίνακα `ids = [101, 102, 103, 104, 105]` με `dtype=int32`.
Πως φτιάχνετε; ids = np.array([101,102,103,104,105], dtype=np.int32)
2. Φτιάξε έναν 2D πίνακα `base_people` για 5 άτομα με στήλες `[ύψος_cm, βάρος_kg]`.
   Δώσε δικές σου τιμές, π.χ.  

   `[[185, 75], [170, 68], [192, 82], [178, 70], [175, 77]]`
3. Φτιάξε έναν 3D πίνακα `groups` σχήματος `(3, 5, 2)` όπου ο άξονας-0 είναι η ομάδα (0..2).
   Χρησιμοποίησε παραλλαγές του `base_people` (π.χ. πρόσθεσε/αφαίρεσε λίγα εκατοστά/κιλά με broadcasting).
4. Δημιούργησε με `np.arange` και `np.linspace` μικρά βοηθητικά διανύσματα.
5. Φτιάξε `np.zeros((5,2))`, `np.ones((2,2))`, `np.eye(3)` και `np.full((5,), fill_value=100)`.


In [2]:
import numpy as np
from tabulate import tabulate

#------------------------------------------------------------------------
#  1) Φτιάξε έναν 1D πίνακα ids = [101, 102, 103, 104, 105] με dtype=int32.
#     Πως φτιάχνετε; ids = np.array([101,102,103,104,105], dtype=np.int32)
#------------------------------------------------------------------------

ids = np.array([101, 102, 103, 104, 105], dtype=np.int16)
print(f"O 1D πίνακας \n {ids}, \n Με το shape ids.shape {ids.shape} \n")

idsvector1=ids.reshape(len(ids),1)
print(f"O 1D πίνακας ΣΤΗΛΗ \n {idsvector1}, \n Με το shape idsvector1.shape {idsvector1.shape}\n")
print(tabulate(idsvector1, tablefmt="double_grid"),"\n")

idsvector2=ids.reshape(1,len(ids))
print(f"O 1D πίνακας ΓΡΑΜΜΗ \n {idsvector2}, \n Με το shape idsvector2.shape {idsvector2.shape}\n")
print(tabulate(idsvector2, tablefmt="double_grid"),"\n")

#------------------------------------------------------------------------
# 2) Φτιάξε έναν 2D πίνακα base_people για 5 άτομα με στήλες
#    [ύψος_cm, βάρος_kg].   Δώσε δικές σου τιμές, π.χ.
#------------------------------------------------------------------------

[[185, 75], [170, 68], [192, 82], [178, 70], [175, 77]]
base_people = np.array([
    [185, 75],
    [170, 68],
    [192, 82],
    [178, 70],
    [175, 77],
], dtype=np.int32)
print(f"O 2D πίνακας base_people \n {base_people}, \n Με το shape base_people.shape {base_people.shape}\n")

print(tabulate(base_people, tablefmt="double_grid"),"\n")

#Ειδικός μετασχηματισμός για να τυπώσουμε όμορφα τον πίνακα με tabulate class
headers_base_people = ["id", "ύψος_cm", "βάρος_kg"]
# κολλάμε την στήλη ids μπροστά από το base_people
base_people_with_ids = np.column_stack([ids, base_people])
print(tabulate(base_people_with_ids, headers=headers_base_people, tablefmt="double_grid"))

#------------------------------------------------------------------------
# 3)  Φτιάξε έναν 3D πίνακα groups σχήματος (3, 5, 2) όπου ο άξονας-0
#     είναι η ομάδα (0..2). Χρησιμοποίησε παραλλαγές του base_people
#     (π.χ. πρόσθεσε/αφαίρεσε λίγα εκατοστά/κιλά με broadcasting).
#------------------------------------------------------------------------

offsets = np.array([
     [ 0,  0],
     [-2, +2],
     [+3, -2],
 ], dtype=np.int16)
print(f"O 2D πίνακας offsets \n {offsets}, \n Με το shape offsets.shape {offsets.shape} \n")
print(tabulate(offsets, tablefmt="double_grid"),"\n")
offsets=offsets.reshape(3,1,2)
print(f"O 2D πίνακας offsets με reshape(3,1,2) \n {offsets}, \n Με το shape offsets.shape {offsets.shape} \n")

# Τυπώνουμε τα offsets για κάθε ομάδα
for i, group in enumerate(offsets):
    print(f"Offsets για την Ομάδα {i}")
    print(tabulate(group, tablefmt="double_grid"), "\n")

# O groups πίνακας γίνεται διάστασης (1,5,2)
groups = base_people[None, :, :]
print(f"groups = base_people[None, :, :]\n {groups}, \n Με το shape groups.shape {groups.shape} \n")
# Τώρα το Broadcasting
# O groups πίνακας διάστασης (1,5,2)
# O πίνακας offsets διάστασης (3,1,2)
# Το broadcasting είναι εφικτό επειδή οι διαστάσεις
#  (3,1,2) και (1,5,2) είναι συμβατές
#  και "επεκτείνονται" αυτόματα σε κοινό σχήμα (3,5,2).
groups=groups+offsets
print(f"groups= groups + offsets \n {groups}, \n Με το shape groups.shape {groups.shape} \n")
# Θα το κάνω τώρα χωρίς επανάλληψη
# for i, group in enumerate(groups):
#     print(f"Ομάδα {i}")
#     print(tabulate(group, tablefmt="double_grid"), "\n")

print("Ομάδα 0")
print(tabulate(groups[0], tablefmt="double_grid"), "\n")

print("Ομάδα 1")
print(tabulate(groups[1], tablefmt="double_grid"), "\n")

print("Ομάδα 2")
print(tabulate(groups[2], tablefmt="double_grid"), "\n")

#------------------------------------------------------------------------
# 4) Δημιούργησε με np.arange και np.linspace μικρά βοηθητικά διανύσματα.
#------------------------------------------------------------------------

v1 = np.arange(0, 10, 2, dtype=np.int32)
print(f"v1 = np.arange(0, 10, 2, dtype=np.int32)\n {v1}, \n Με το shape groups.shape {v1.shape} \n")
print(tabulate(v1.reshape(1,len(v1)), tablefmt="double_grid"),"\n")
v2 = np.linspace(0.0, 1.0, num=5)
print(f"v2 = np.linspace(0.0, 1.0, num=5)\n {v2}, \n Με το shape groups.shape {v2.shape} \n")
print(tabulate(v2.reshape(1,len(v2)), tablefmt="double_grid"),"\n")

#------------------------------------------------------------------------
# 5) Φτιάξε np.zeros((5,2)), np.ones((2,2)),
#           np.eye(3) και np.full((5,), fill_value=100).
#------------------------------------------------------------------------

Z = np.zeros((5, 2))
print(f"Z = np.zeros((5, 2))\n {Z}, \n Με το shape groups.shape {Z.shape} \n")
print(tabulate(Z, tablefmt="double_grid"),"\n")

O = np.ones((2, 2), dtype=np.int8)
print(f"O = np.ones((2, 2), dtype=np.int8)\n {O}, \n Με το shape groups.shape {O.shape} \n")
print(tabulate(O, tablefmt="double_grid"),"\n")

I = np.eye(3, dtype=np.int8)
print(f"I = np.eye(3, dtype=np.int8)\n {I}, \n Με το shape groups.shape {I.shape} \n")
print(tabulate(I, tablefmt="double_grid"),"\n")

F = np.full((5,), fill_value=100, dtype=np.int32)
print(f"F = np.full((5,), fill_value=100, dtype=np.int32)\n {F}, \n Με το shape groups.shape {F.shape} \n")
print(tabulate(F.reshape(1,len(F)), tablefmt="double_grid"),"\n")


O 1D πίνακας 
 [101 102 103 104 105], 
 Με το shape ids.shape (5,) 

O 1D πίνακας ΣΤΗΛΗ 
 [[101]
 [102]
 [103]
 [104]
 [105]], 
 Με το shape idsvector1.shape (5, 1)

╔═════╗
║ 101 ║
╠═════╣
║ 102 ║
╠═════╣
║ 103 ║
╠═════╣
║ 104 ║
╠═════╣
║ 105 ║
╚═════╝ 

O 1D πίνακας ΓΡΑΜΜΗ 
 [[101 102 103 104 105]], 
 Με το shape idsvector2.shape (1, 5)

╔═════╦═════╦═════╦═════╦═════╗
║ 101 ║ 102 ║ 103 ║ 104 ║ 105 ║
╚═════╩═════╩═════╩═════╩═════╝ 

O 2D πίνακας base_people 
 [[185  75]
 [170  68]
 [192  82]
 [178  70]
 [175  77]], 
 Με το shape base_people.shape (5, 2)

╔═════╦════╗
║ 185 ║ 75 ║
╠═════╬════╣
║ 170 ║ 68 ║
╠═════╬════╣
║ 192 ║ 82 ║
╠═════╬════╣
║ 178 ║ 70 ║
╠═════╬════╣
║ 175 ║ 77 ║
╚═════╩════╝ 

╔══════╦═══════════╦════════════╗
║   id ║   ύψος_cm ║   βάρος_kg ║
╠══════╬═══════════╬════════════╣
║  101 ║       185 ║         75 ║
╠══════╬═══════════╬════════════╣
║  102 ║       170 ║         68 ║
╠══════╬═══════════╬════════════╣
║  103 ║       192 ║         82 ║
╠══════╬═══════════

## 2) Shapes, άξονες & αναδιατάξεις (reshape)

1. Εξήγαγε `shape`, `ndim`, `dtype` για `groups`.

2. Κάνε `reshape` έναν 2D πίνακα σε 1D και πίσω σε 2D (δες ότι συμβατή διάσταση απαιτείται).

3. Πάρε την *πρώτη ομάδα* `groups[0]` και έλεγξε σχήμα & τύπους.



In [3]:
#----------------------------------------------
#  1)  Εξήγαγε shape, ndim, dtype για groups.
#----------------------------------------------
print("------"*10)
print(f"groups.shape = {groups.shape} \n")
print(f"groups.ndim = {groups.ndim} \n")
print(f"groups.dtype = {groups.dtype} \n")

#----------------------------------------------
# 2) Κάνε reshape έναν 2D πίνακα σε 1D και πίσω σε 2D
#    (δες ότι συμβατή διάσταση απαιτείται).
#----------------------------------------------
print("------"*10)
print(f"groups[0].shape = {groups[0].shape}  \n")

groupA=groups[0].reshape(-1)
print(groupA)
print(f"groupA=groups[0].reshape(-1) groupA.shape = {groupA.shape} \n")
print(f"groupA.ndim = {groupA.ndim} \n")
print(f"groupA.dtype = {groupA.dtype} \n")

groupA=groupA.reshape(5,2)
print(groupA)
print(f"groupA=groupA.reshape(5,2) groupA.shape = {groupA.shape} \n")
print(f"groupA.ndim = {groupA.ndim} \n")
print(f"groupA.dtype = {groupA.dtype} \n")

print("------"*10)
#----------------------------------------------
# 3) Πάρε την πρώτη ομάδα groups[0] και έλεγξε σχήμα & τύπους.
#----------------------------------------------
print(f"groups[0].shape = {groups[0].shape} \n")
print(f"groups[0].ndim = {groups[0].ndim} \n")
print(f"groups[0].dtype = {groups[0].dtype} \n")







------------------------------------------------------------
groups.shape = (3, 5, 2) 

groups.ndim = 3 

groups.dtype = int32 

------------------------------------------------------------
groups[0].shape = (5, 2)  

[185  75 170  68 192  82 178  70 175  77]
groupA=groups[0].reshape(-1) groupA.shape = (10,) 

groupA.ndim = 1 

groupA.dtype = int32 

[[185  75]
 [170  68]
 [192  82]
 [178  70]
 [175  77]]
groupA=groupA.reshape(5,2) groupA.shape = (5, 2) 

groupA.ndim = 2 

groupA.dtype = int32 

------------------------------------------------------------
groups[0].shape = (5, 2) 

groups[0].ndim = 2 

groups[0].dtype = int32 



## 3) Δεικτοδότηση & slicing

1. Πάρε το ύψος του 3ου ατόμου της 2ης ομάδας.




In [4]:
print(f"το ύψος του 3ου ατόμου της 2ης ομάδας είναι {groups[1,2,0]} cm \n")


το ύψος του 3ου ατόμου της 2ης ομάδας είναι 190 cm 



## 4) Μάσκες boolean & φιλτράρισμα

1. Βρες όλα τα άτομα (σε **όλες** τις ομάδες) με ύψος `>= 180cm`.

2. Βρες πόσα άτομα έχουν βάρος στο διάστημα `[70, 80]`.

3. Σήκωσε μάσκα που να είναι `True` όπου το BMI > 25. (Υπόδειξη: `BMI = βάρος_kg / (ύψος_m ** 2)`)

   *Χρησιμοποίησε broadcasting για να μετατρέψεις ύψος σε μέτρα.*


In [5]:
# -------------------------------
# 1) Όλα τα άτομα (σε όλες τις ομάδες) με ύψος >= 180 cm
# -------------------------------
height_cm = groups[..., 0]
print(height_cm)

mask_tall = height_cm >= 180
print(mask_tall)

g_idx, p_idx = np.where(mask_tall)
print(g_idx)
print(p_idx)

print("Ύψος >= 180cm — πλήθος:", mask_tall.sum())

print("Δείκτες (group, person):")
print(np.column_stack([g_idx, p_idx]))     # λίστα δεικτών
tall_vals = groups[g_idx, p_idx, :]
print("(ύψος_cm, βάρος_kg) για όσους είναι >=180cm:\n", tall_vals)

result = np.column_stack([g_idx, p_idx, tall_vals])
print(tabulate(result, headers=["group", "person", "ύψος_cm", "βάρος_kg"], tablefmt="rounded_grid"))

# -------------------------------
# 2) Πόσα άτομα έχουν βάρος στο [70, 80]
# -------------------------------
weight_kg = groups[..., 1]
print(weight_kg)
mask_w = (weight_kg >= 70) & (weight_kg <= 80)
print(mask_w)
g_widx, p_widx = np.where(mask_w)
print(g_widx)
print(p_widx)
print("\nΒάρος στο [70,80] — σύνολο:", mask_w.sum())
print("Δείκτες (group, person):")
print(np.column_stack([g_widx, p_widx]))     # λίστα δεικτών
weight_values=groups[g_widx,p_widx, :]
print(weight_values)
result_w = np.column_stack([g_widx, p_widx, weight_values])
print(tabulate(result_w, headers=["group", "person", "ύψος_cm", "βάρος_kg"], tablefmt="rounded_grid"))
# Αν θέλω να τυπώσω μόνον την ομάδα 2 η στήλη "group" == 1
mask_group2 = result_w[:, 0] == 1
print(result_w[:,0])
group2 = result_w[mask_group2]

print(tabulate(group2,
               headers=["group", "person", "ύψος_cm", "βάρος_kg"],
               tablefmt="rounded_grid"))

print("Ανά ομάδα:", mask_w.sum(axis=1))

# -------------------------------
# 3) Μάσκα BMI > 25
#    BMI = βάρος_kg / (ύψος_m ** 2)
# -------------------------------
# 4) Broadcasting
height_m = height_cm / 100.0
print("------"*10)
print(height_cm)
bmi = weight_kg / (height_m ** 2)
print(bmi)
mask_bmi = bmi > 25
print(mask_bmi)

print("\nBMI > 25 — σύνολο:", mask_bmi.sum())
print("Ανά ομάδα:", mask_bmi.sum(axis=1))

# (group, person, BMI) για όσους έχουν BMI>25
gi, pi = np.where(mask_bmi)
print("\nΔείκτες (group, person) με BMI>25:")
print(np.column_stack([gi, pi]))
print("BMI τιμές για αυτούς:\n", bmi[gi, pi])
result_bmi = np.column_stack([gi, pi, bmi[gi, pi], groups[gi, pi, :]])
print(result_bmi)
print(tabulate(result_bmi,
               headers=["group", "person", "BMI", "ύψος_cm", "βάρος_kg"],
               tablefmt="rounded_grid"))


[[185 170 192 178 175]
 [183 168 190 176 173]
 [188 173 195 181 178]]
[[ True False  True False False]
 [ True False  True False False]
 [ True False  True  True False]]
[0 0 1 1 2 2 2]
[0 2 0 2 0 2 3]
Ύψος >= 180cm — πλήθος: 7
Δείκτες (group, person):
[[0 0]
 [0 2]
 [1 0]
 [1 2]
 [2 0]
 [2 2]
 [2 3]]
(ύψος_cm, βάρος_kg) για όσους είναι >=180cm:
 [[185  75]
 [192  82]
 [183  77]
 [190  84]
 [188  73]
 [195  80]
 [181  68]]
╭─────────┬──────────┬───────────┬────────────╮
│   group │   person │   ύψος_cm │   βάρος_kg │
├─────────┼──────────┼───────────┼────────────┤
│       0 │        0 │       185 │         75 │
├─────────┼──────────┼───────────┼────────────┤
│       0 │        2 │       192 │         82 │
├─────────┼──────────┼───────────┼────────────┤
│       1 │        0 │       183 │         77 │
├─────────┼──────────┼───────────┼────────────┤
│       1 │        2 │       190 │         84 │
├─────────┼──────────┼───────────┼────────────┤
│       2 │        0 │       188 │         73

## 5) Στατιστικά & συναρτήσεις συγκέντρωσης (axis)

1. Υπολόγισε `min`, `max`, `mean`, `median`, `std` για τα ύψη **κατά ομάδα** (`axis=1`).

2. Υπολόγισε `sum` βαρών **ανά ομάδα** και **στο σύνολο**.

3. Δείξε πώς αλλάζει το αποτέλεσμα όταν αλλάζεις τον `axis`.



In [7]:
# 1) Υπολόγισε min, max, mean, median, std για τα ύψη κατά ομάδα (axis=1).
# # Παράδειγμα
# groups = np.array([
#     [[185, 75], [170, 68], [192, 82], [178, 70], [175, 77]],
#     [[183, 74], [168, None], [190, 81], [176, np.nan], [172, 78]],
#     [[188, 76], [173, 69], [195, np.nan], [182, 71], [179, 80]]
# ], dtype=object)

# ---- Επιλογή ύψους ----
height = np.array(groups[..., 0], dtype=object)

# ---- Καθαρισμός None/NaN ανά ομάδα ----
def clean_group(values):
    # Αφαιρεί None και NaN και επιστρέφει float array
    clean = [x for x in values if not ((x is None) or (isinstance(x, float) and np.isnan(x)))]
    return np.array(clean, dtype=float)

# Υπολογισμός στατιστικών ανά ομάδα με ασφαλή τρόπο
stats = []
for i, row in enumerate(height):
    clean = clean_group(row)
    if clean.size > 0:
        stats.append([
            i,
            np.min(clean),
            np.max(clean),
            np.mean(clean),
            np.median(clean),
            np.std(clean)
        ])
    else:
        # Αν η ομάδα είναι κενή ή μόνο με NaN
        stats.append([i, np.nan, np.nan, np.nan, np.nan, np.nan])

# ---- Δημιουργία πίνακα ----
data = np.array(stats, dtype=float)
headers = ["Ομάδα", "min", "max", "mean", "median", "std"]

print(tabulate(data, headers=headers, tablefmt="rounded_grid", floatfmt=".0f"))

# 2) Υπολόγισε `sum` βαρών **ανά ομάδα** και **στο σύνολο**.

# ---- Επιλογή ύψους ----
Weight = np.array(groups[..., 1], dtype=object)
statsW = []
for i, row in enumerate(Weight):
    cleanW = clean_group(row)
    if cleanW.size > 0:
        statsW.append([
            i,
            np.sum(cleanW),
          ])
    else:
        # Αν η ομάδα είναι κενή ή μόνο με NaN
        statsW.append([i, np.nan])
dataW = np.array(statsW, dtype=float)
headersW = ["Ομάδα", "sum"]


print(tabulate(dataW, headers=headersW, tablefmt="rounded_grid", floatfmt=".0f"))
total_weight = np.nansum(dataW[:, 1])
print("Συνολικό βάρος όλων των ομάδων:", total_weight)
total_weight = np.nansum(groups[...,1],axis=1)
print("Συνολικό βάρος ανα ομάδα:", total_weight)
total_weight = np.nansum(groups[...,1])
print("Συνολικό βάρος όλων των ομάδων:", total_weight)
print("----"*10)
print("----"*10)
print(groups.ndim)

print("Ομάδα 0")
print(tabulate(groups[0], tablefmt="double_grid"), "\n")

print("Ομάδα 1")
print(tabulate(groups[1], tablefmt="double_grid"), "\n")

print("Ομάδα 2")
print(tabulate(groups[2], tablefmt="double_grid"), "\n")

test_axis1  = np.nansum(groups, axis=0)
print("for axis = 0 :", test_axis1)
print(tabulate(test_axis1, tablefmt="double_grid"), "\n")

test_axis2 = np.nansum(groups, axis=1)
print("for axis = 1 :", test_axis2)
print(tabulate(test_axis2, tablefmt="double_grid"), "\n")

test_axis3 = np.nansum(groups, axis=2)
print("for axis = 2 :", test_axis3)
print(tabulate(test_axis3, tablefmt="double_grid"), "\n")

test_axis4 = np.nansum(groups, axis=(0,1))
print("for axis = (0,1) :", test_axis4)
# print(tabulate(test_axis4, tablefmt="double_grid"), "\n")

test_axis5 = np.nansum(groups, axis=(0,2))
print("for axis = (0,2) :", test_axis5)
# print(tabulate(test_axis5, tablefmt="double_grid"), "\n")

test_axis6 = np.nansum(groups, axis=(1,2))
print("for axis = (1,2) :", test_axis6)
# print(tabulate(test_axis6, tablefmt="double_grid"), "\n")

test_axis7 = np.nansum(groups, axis=(0,1,2))
print("for axis = (0,1,2) :", test_axis7)

test_axis8 = np.nansum(groups)
print("for no axis :", test_axis8)
print(f"for axis = (0,1,2) and no axis scalar equal{test_axis7==test_axis8} \n")


╭─────────┬───────┬───────┬────────┬──────────┬───────╮
│   Ομάδα │   min │   max │   mean │   median │   std │
├─────────┼───────┼───────┼────────┼──────────┼───────┤
│       0 │   170 │   192 │    180 │      178 │     8 │
├─────────┼───────┼───────┼────────┼──────────┼───────┤
│       1 │   168 │   190 │    178 │      176 │     8 │
├─────────┼───────┼───────┼────────┼──────────┼───────┤
│       2 │   173 │   195 │    183 │      181 │     8 │
╰─────────┴───────┴───────┴────────┴──────────┴───────╯
╭─────────┬───────╮
│   Ομάδα │   sum │
├─────────┼───────┤
│       0 │   372 │
├─────────┼───────┤
│       1 │   382 │
├─────────┼───────┤
│       2 │   362 │
╰─────────┴───────╯
Συνολικό βάρος όλων των ομάδων: 1116.0
Συνολικό βάρος ανα ομάδα: [372 382 362]
Συνολικό βάρος όλων των ομάδων: 1116
----------------------------------------
----------------------------------------
3
Ομάδα 0
╔═════╦════╗
║ 185 ║ 75 ║
╠═════╬════╣
║ 170 ║ 68 ║
╠═════╬════╣
║ 192 ║ 82 ║
╠═════╬════╣
║ 178 ║ 70 ║
╠═══

## 6) Συνένωση (stack) & Διαίρεση (split)

1. Στοίβαξε τις 3 ομάδες σε έναν 2D πίνακα `all_people` σχήματος `(15, 2)` με `np.vstack` ή `reshape`.

2. Κόψε τον `all_people` σε 3 ίσα μέρη των `(5, 2)` με `np.split`.

3. Δείξε `np.concatenate` οριζόντια και κατακόρυφα (π.χ. πρόσθεσε μια στήλη/χαρακτηριστικό).



In [8]:
# 1) Στοίβαξε τις 3 ομάδες σε έναν 2D πίνακα (15,2)
# α τροπος με reshape
all_people = groups.reshape(-1, 2)
print("---reshape(-1,2)", all_people)
# β τροπος με vstack
all_people_v = np.vstack([groups[0], groups[1], groups[2]])
print("vstack",all_people_v)
# Σύγκριση των πινάκων με α τροπος και β τρόπο
print("Οι πίνακες που έφταξα με reshape και vstack είναι ίδιοι")
print(np.array_equal(all_people, all_people_v, equal_nan=True))

# ---------------------------------------------------------------
# 2) Κόψε τον all_people σε 3 ίσα μέρη των (5, 2) με np.split.
parts = np.split(all_people, 3, axis=0)    # λίστα 3 στοιχείων, το καθένα (5,2)
# Τώρα θα ξανασυνθέσω την κομμένη λίστα στην again_all_people
again_all_people= np.vstack([parts[0], parts[1], parts[2]])
print("Ο πίνακας που προέκειψε από τα κομματια της λίστας vsplit")
print("που συγχώνευσα ξανα με vstack είναι ίδιος με τον αρχικό πίνακα")
print(np.array_equal(all_people, again_all_people, equal_nan=True))

# ---------------------------------------------------------------
# 3) np.concatenate οριζόντια (axis=1) και κατακόρυφα (axis=0)
p0, p1, p2 = parts
print("\n p0 \n", p0, "\n p1 \n", p1, "\n p2 \n", p2," \n ","_________"*10," \n ")

vert_cat = np.concatenate([p0, p1, p2], axis=0)  # (15,2) — ίδια #στηλών
print("\n np.concatenate([p0, p1, p2], axis=0) \n", vert_cat," \n ","_________"*10," \n ")
print("\n Ο πίνακας που προέκειψε από τα κομματια της λίστας vsplit")
print("p0,p1,p2 που συνένωσα με συγχώνευσα np.concatenate([p0, p1, p2], axis=0) είναι ίδιος με τον αρχικό πίνακα")
print(np.array_equal(all_people, vert_cat, equal_nan=True))

# Φτιάχνω τεσσερεις νεες στήλες ύψος σε cm, βάρος, bmi και height σε m
vert_cat_height_cm= vert_cat[:, 0]
vert_cat_height_cm = vert_cat_height_cm.reshape(-1,1)
vert_cat_height= vert_cat[:, 0] / 100.0
vert_cat_height = vert_cat_height.reshape(-1,1)
vert_cat_weight = vert_cat[:, 1]
vert_cat_weight = vert_cat_weight.reshape(-1,1)
vert_cat_bmi = (vert_cat_weight / (vert_cat_height**2))
vert_cat_bmi = vert_cat_bmi.reshape(-1,1)
print("\n ", vert_cat_bmi," \n ","_________"*10," \n ")
vert_cat_with_bmi = np.concatenate([vert_cat_weight,vert_cat_height_cm,vert_cat_height, vert_cat_bmi], axis=1)
print("\n ", vert_cat_with_bmi," \n ","_________"*10," \n ")
headersvert_bmi = ["Βάρος σε κιλά", "Ύψος σε cm", "Ύψος σε m", "Δείκτης Μάζας Σώματος"]
print(tabulate(vert_cat_with_bmi, headers=headersvert_bmi, tablefmt="rounded_grid", floatfmt=".2f"))



---reshape(-1,2) [[185  75]
 [170  68]
 [192  82]
 [178  70]
 [175  77]
 [183  77]
 [168  70]
 [190  84]
 [176  72]
 [173  79]
 [188  73]
 [173  66]
 [195  80]
 [181  68]
 [178  75]]
vstack [[185  75]
 [170  68]
 [192  82]
 [178  70]
 [175  77]
 [183  77]
 [168  70]
 [190  84]
 [176  72]
 [173  79]
 [188  73]
 [173  66]
 [195  80]
 [181  68]
 [178  75]]
Οι πίνακες που έφταξα με reshape και vstack είναι ίδιοι
True
Ο πίνακας που προέκειψε από τα κομματια της λίστας vsplit
που συγχώνευσα ξανα με vstack είναι ίδιος με τον αρχικό πίνακα
True

 p0 
 [[185  75]
 [170  68]
 [192  82]
 [178  70]
 [175  77]] 
 p1 
 [[183  77]
 [168  70]
 [190  84]
 [176  72]
 [173  79]] 
 p2 
 [[188  73]
 [173  66]
 [195  80]
 [181  68]
 [178  75]]  
  __________________________________________________________________________________________  
 

 np.concatenate([p0, p1, p2], axis=0) 
 [[185  75]
 [170  68]
 [192  82]
 [178  70]
 [175  77]
 [183  77]
 [168  70]
 [190  84]
 [176  72]
 [173  79]
 [188  73]
 [173  

## 7) Ταξινόμηση & ευρετήρια ακραίων

1. Ταξινόμησε τα άτομα εντός κάθε ομάδας με βάση το ύψος (αύξοντα). Δείξε και `np.argsort`.

2. Βρες τη θέση (`argmax`) του ψηλότερου ατόμου **σε κάθε ομάδα**.



In [9]:
# ==========================================
#  Εκτύπωση των ομάδων
# ==========================================
for i, g in enumerate(groups):
    print(f"Ομάδα {i}")
    print(tabulate(g, headers=['Ύψος(cm)', 'Βάρος(kg)'], tablefmt='rounded_grid'), "\n")
# ==========================================
#  Δείκτες ταξινόμησης ανά ομάδα βάσει ύψους
# ==========================================
sort_idx = np.argsort(groups[:, :, 0], axis=1)
print("\n",groups[:, :, 0], "\n","shape groups[:, :, 0] = ", np.shape(groups[:, :, 0]))
print("Δείκτες ταξινόμησης ανά ομάδα (argsort):")
print("\n",sort_idx, "\n","shape = ", sort_idx.shape)

# =========================================
#  Ταξινομημένες ομάδες (ύψος σε αύξουσα σειρά)
# ==========================================
print("sort_idx[..., None]",sort_idx[..., None],np.shape(sort_idx[...,None]))
sorted_groups = np.take_along_axis(groups, sort_idx[..., None], axis=1)
print("Ταξινομημένες ομάδες κατά ύψος:")
for i, g in enumerate(sorted_groups):
     print(f"Ομάδα {i}")
     print(tabulate(g, headers=['Ύψος(cm)', 'Βάρος(kg)'], tablefmt='rounded_grid'), "\n")

# ==========================================
#  Θέση του ψηλότερου ατόμου (argmax)
# ==========================================
max_idx = np.argmax(groups[:, :, 0], axis=1)
print("Δείκτης (θέση) ψηλότερου ατόμου σε κάθε ομάδα:", max_idx)

# ==========================================
#  Τιμές του ψηλότερου ατόμου ανά ομάδα
# ==========================================
tallest_people = groups[np.arange(groups.shape[0]), max_idx, :]
for i, g in enumerate(tallest_people):
     print(f"Ο ψηλότερος για την Ομάδα {i}")
     print(tabulate(g.reshape(-1,2), headers=['Ύψος(cm)', 'Βάρος(kg)'], tablefmt='rounded_grid'), "\n")



Ομάδα 0
╭────────────┬─────────────╮
│   Ύψος(cm) │   Βάρος(kg) │
├────────────┼─────────────┤
│        185 │          75 │
├────────────┼─────────────┤
│        170 │          68 │
├────────────┼─────────────┤
│        192 │          82 │
├────────────┼─────────────┤
│        178 │          70 │
├────────────┼─────────────┤
│        175 │          77 │
╰────────────┴─────────────╯ 

Ομάδα 1
╭────────────┬─────────────╮
│   Ύψος(cm) │   Βάρος(kg) │
├────────────┼─────────────┤
│        183 │          77 │
├────────────┼─────────────┤
│        168 │          70 │
├────────────┼─────────────┤
│        190 │          84 │
├────────────┼─────────────┤
│        176 │          72 │
├────────────┼─────────────┤
│        173 │          79 │
╰────────────┴─────────────╯ 

Ομάδα 2
╭────────────┬─────────────╮
│   Ύψος(cm) │   Βάρος(kg) │
├────────────┼─────────────┤
│        188 │          73 │
├────────────┼─────────────┤
│        173 │          66 │
├────────────┼─────────────┤
│        195 │ 

## 8) Broadcasting (κεντράρισμα/κανονικοποίηση)

1. Υπολόγισε το **μέσο** ύψος και βάρος.





In [1]:
# Ύψος & βάρος
height = groups[:, :, 0]          # (3,5)
weight = groups[:, :, 1]          # (3,5)

# Μέσοι όροι (ολικά)
mean_h = np.nanmean(height)          # ή np.nanmean(...)
mean_w = np.nanmean(weight)

print(f"Ο μέσος όρος ύψους είναι:  {mean_h:.3f} cm")
print(f"Ο μέσος όρος βάρους είναι:  {mean_w:.3f} κιλά")


NameError: name 'groups' is not defined

## 9) Τυχαία δειγματοληψία

1. Δημιούργησε `n=4` τυχαία άτομα επιλέγοντας *γραμμές* από `all_people` με `np.random.choice` χωρίς αντικατάσταση.

2. Υπολόγισε τον μέσο όρο ύψους/βάρους στο τυχαίο δείγμα.



In [130]:
all_people = groups.reshape(-1, 2)
n = 4  # μέγεθος δείγματος
print(np.shape(all_people))
# Επιλογή 4 τυχαίων γραμμών χωρίς επανατοποθέτηση (διαφορετικές)
idx = np.random.choice(all_people.shape[0], size=n, replace=False)
sample = all_people[idx, :]   # οι 4 γραμμές του δείγματος

# Υπολογισμός μέσου όρου ύψους/βάρους στο δείγμα
mean_h = np.nanmean(sample[:, 0])
mean_w = np.nanmean(sample[:, 1])

print("Τυχαίο δείγμα 4 ατόμων:")
print(tabulate(sample, headers=["Ύψος (cm)", "Βάρος (kg)"], tablefmt="rounded_grid"))

print(f"\nΜέσο ύψος δείγματος:  {mean_h:.2f} εκατοστά")
print(f"Μέσο βάρος δείγματος: {mean_w:.2f} κιλά")

(15, 2)
Τυχαίο δείγμα 4 ατόμων:
╭─────────────┬──────────────╮
│   Ύψος (cm) │   Βάρος (kg) │
├─────────────┼──────────────┤
│         178 │           70 │
├─────────────┼──────────────┤
│         173 │           79 │
├─────────────┼──────────────┤
│         170 │           68 │
├─────────────┼──────────────┤
│         175 │           77 │
╰─────────────┴──────────────╯

Μέσο ύψος δείγματος:  174.00 εκατοστά
Μέσο βάρος δείγματος: 73.50 κιλά
